### ISSUE TITLE
Runnable interface doesn't match Deno's promise type

### ISSUE THREAD

**Issue by Jelledb** [alextes/run_with_limit#2]
Hi, I just tried using this library but my compiler is complaining about the type signature of `resolve`:

```
error: TS2322 [ERROR]: Type '(value: A | PromiseLike<A>) => void' is not assignable to type '(value?: A | PromiseLike<A> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'A | PromiseLike<A> | undefined' is not assignable to type 'A | PromiseLike<A>'.
      Type 'undefined' is not assignable to type 'A | PromiseLike<A>'.
      enqueue({ fn, resolve, reject })
                    ~~~~~~~
    at https://deno.land/x/run_with_limit@v0.1.0/mod.ts:50:21
```

Is it possible to fix this by slightly changing the `Runnable` interface?

**Comment by Jelledb** [comment]
The code I used is open-source btw, maybe it helps: https://github.com/meshcloud/collie-cli/pull/14/files

**Comment by alextes** [comment]
@Jelledb had me puzzled there for a bit haha. It appears I never pushed the latest tag. You can update to the `v1.0.1` tag which should solve things.

Thanks for reporting 👍 !
